### ISSUE TITLE
Question: Removing Bootstrap & JQuery-Dependency

### ISSUE THREAD

**Issue by ChrisB9** [nambu-ch/pimcore-image-loader#1]
This project looks very promising and I would like to use it in my clients website.

I just have a major conflict with my own project:
I do not use either bootstrap nor jQuery and this library is built around it.

Would you consider an implementation without the reliance on those two libraries?

**Comment by dominikschnieper** [comment]
Thanks for your interest in the project.

The bootstrap part is easy, it is only one css selector (`.img-fluid { max-width: 100%; height: auto;}`) which you have to integrate in your css. There is no need to integrate bootstrap besides that.

We have no short term plan to remove the jQuery dependency. But we are open for a pull request to remove that.

**Comment by lukas-schnieper** [comment]
There is now a version without jquery as dependency since v2.1.3
